// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc4678.walle.commands;

import edu.wpi.first.wpilibj.Preferences;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc4678.walle.Robot;

/**
 *
 */
public class  ManuallyAdjustPotValues extends Command {

	double leftY = 0;
	double rightY = 0;
	
    public ManuallyAdjustPotValues() {
        // Use requires() here to declare subsystem dependencies
        // eg. requires(chassis);

        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    protected void initialize() {
    }

    // Called repeatedly when this Command is scheduled to run
    protected void execute() {
    	leftY = Robot.oi.getGamepad2().getRawAxis(1);
    	rightY = Robot.oi.getGamepad2().getRawAxis(3);
    	
    	if (leftY < 0.1) {
    		leftY = 0;
    	}
    	
    	if (rightY < 0.1) {
    		rightY = 0;
    	}
    	
    	Preferences prefs = Preferences.getInstance();
    	prefs.putDouble("armPotOffset", Robot.armPotOffset() + (leftY / 100));
    	prefs.putDouble("pickupPotOffset", Robot.pickupPotOffset() + (rightY / 100));
    }

    // Make this return true when this Command no longer needs to run execute()
    protected boolean isFinished() {
        return false;
    }

    // Called once after isFinished returns true
    protected void end() {
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    protected void interrupted() {
    }
}
